language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
before_install:
  - "npm install -g lineman"
  - "cd front_end && npm install"
  - "lineman build"
  - "cd .."
