language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-19mode
before_install:
  - npm install -g lineman
  - cd front_end 
  - npm install
  - npm install protractor
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar
  - java -jar selenium-server-standalone-2.31.0.jar &
  - lineman build
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cd ..
script:
  - bundle exec rake
  - cd front_end
  - lineman run &
  - lineman spec-ci
  - ./node_modules/protractor/bin/protractor config/spec-e2e.js
  - cd ..